from datetime import datetime
from datetime import date
from datetime import time
from datetime import timedelta
import locale

d1 = date(2019, 3, 10)
print(d1)
time1 = time(23, 10, 10)
print(time1)
print(date.today())
print(date.max)
print(date.min)
print(time.max)
print(time.min)
dt = datetime(29, 10, 10, 10, 10, 10)
print(dt)
print(datetime.today())
print(dt.date().day)
print(datetime.now())
dt_temp = dt.now().replace(year=2000)
print(dt_temp)
dt3 = datetime.strptime("30/08/2018", "%d/%m/%Y")
print(dt3)
dt4 = datetime.strptime("29/03/2000/10/03/50", "%d/%m/%Y/%H/%M/%S")
print(dt4)
locale.setlocale(locale.LC_ALL, "")
now = datetime.now()
print(now.strftime("%d/%m/%Y %H:%M:%S (%A)"))
print(now.strftime("%d/%B/%Y %H:%M:%S (%a)"))
td = timedelta(days=3, hours=2, minutes=30, seconds=50)
print(td)
td1 = timedelta(days=1, hours=1, minutes=20, seconds=20)
print(td1)
print(td-td1)
