print(abs(-1))
print(max(1, 2, 3, 4))
print(max([1, 2, 3, 4]))
print(pow(2, 8))
print(round(3.335, 1))
print(sum([1, 2, 3]))
print(hex(10))
print(oct(10))
print(bin(10))
print(all([True, False]))
print(all([True, True]))
print(any([False, False, True]))
print(any([False, False, False]))
letter = "abc"
numbers = (10, 20, 30)
z = zip(letter, numbers)
print(list(z))
print(ord('a'))
print(chr(97))
